Just a little change to better adapt to cmp output format variation..
See below 2 (real) examples and see differences in cmp output format..:

vladi@VladiLaptop1W10 /cygdrive/c/Users/mvman/Downloads/tmp1/tmp1/tmp1/tmp/png2svg
$ cmp -bl fc2Id0U8.png fc2Id0U8_2.png
43493 335 M-]  163 s
44198 171 y    311 M-I
45924   0 ^@     1 ^A
47543 165 u    253 M-+
47944 344 M-d   15 ^M
48889  71 9      7 ^G
vladi@VladiLaptop1W10 /cygdrive/c/Users/mvman/Downloads/tmp1/tmp1/tmp1/tmp/png2svg
$ cmp -bl fc2Id0U8.png fc2Id0U8_2.png|cmpbl2hex
a9e4  dd M-]    73 s
aca5  79 y      c9 M-I
b363   0 ^@      1 ^A
b9b6  75 u      ab M-+
bb47  e4 M-d     d ^M
bef8  39 9       7 ^G

# 2nd example.. Note the blank gap at the beginning of each cmp output row..:
vladi@VladiLaptop1W10 /cygdrive/c/Users/mvman
$ cmp -bl "VladiDocuments/Finance/tmp1/BILANT PRESCURTAT 2014.xls" "VldTmp1/VladiDocuments/Finance/tmp1/BILANT PRESCURTAT 2014.xls"
  1133 360 M-p  200 M-^@
  1134 215 M-^M  16 ^N
  1135 120 P    253 M-+
  1136 371 M-y   36 ^^
  1137 211 M-^I 335 M-]
  1138 240 M-     4 ^D
  1139 331 M-Y  330 M-X
# With the previous commit:
vladi@VladiLaptop1W10 /cygdrive/c/Users/mvman
$ cmp -bl "VladiDocuments/Finance/tmp1/BILANT PRESCURTAT 2014.xls" "VldTmp1/VladiDocuments/Finance/tmp1/BILANT PRESCURTAT 2014.xls"|cmpbl2hex
Traceback (most recent call last):
  File "/usr/local/bin/cmpbl2hex", line 15, in <module>
    addr, val1, val2 = int(match.group(1)) - 1, int(match.group(3), 8), int(match.group(5), 8)
AttributeError: 'NoneType' object has no attribute 'group'
# Now:
vladi@VladiLaptop1W10 /cygdrive/c/Users/mvman
$ cmp -bl "VladiDocuments/Finance/tmp1/BILANT PRESCURTAT 2014.xls" "VldTmp1/VladiDocuments/Finance/tmp1/BILANT PRESCURTAT 2014.xls"|cmpbl2hex
46c  f0 M-p    80 M-^@
46d  8d M-^M    e ^N
46e  50 P      ab M-+
46f  f9 M-y    1e ^^
470  89 M-^I   dd M-]
471  a0 M-      4 ^D
472  d9 M-Y    d8 M-X